In [1]:
import pandas as pd
import ast
import json
import os

In [2]:
df = pd.read_csv("dataset/movies.csv", usecols=['genres','original_language', 'original_title', 'production_companies', 'production_countries', 'release_date', 'runtime', 'vote_average', 'vote_count'])

print(df.shape)
df = df.dropna()
print(df.shape)

df

(45466, 9)
(45119, 9)

,genres,original_language,original_title,production_companies,production_countries,release_date,runtime,vote_average,vote_count
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",en,Toy Story,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,81.0,7.7,5415.0
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,Jumanji,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,104.0,6.9,2413.0
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",en,Grumpier Old Men,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,101.0,6.5,92.0
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,Waiting to Exhale,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,127.0,6.1,34.0
4,"[{'id': 35, 'name': 'Comedy'}]",en,Father of the Bride Part II,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,106.0,5.7,173.0
...,...,...,...,...,...,...,...,...,...
45460,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",en,Robin Hood,"[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1991-05-13,104.0,5.7,26.0
45462,"[{'id': 18, 'name': 'Drama'}]",tl,Siglo ng Pagluluwal,"[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,360.0,9.0,3.0
45463,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",en,Betrayal,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,90.0,3.8,6.0
45464,[],en,Satana likuyushchiy,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,87.0,0.0,0.0
45465,[],en,Queerama,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,75.0,0.0,0.0

In [3]:
def extract_field(json, field):
    try:
        list_string = ast.literal_eval(json)

        if not isinstance(list_string, list):
            return ""
        
        names=[item.get(field) for item in list_string if isinstance(item, dict) and item.get(field)]

        return ", ".join(names)
    except (SyntaxError, ValueError):
        return ""

In [4]:
df['genres'] = df['genres'].apply(lambda x: extract_field(x, 'name'))
df['production_companies'] = df['production_companies'].apply(lambda x: extract_field(x, 'name'))
df['production_countries'] = df['production_countries'].apply(lambda x: extract_field(x, 'name'))
df

,genres,original_language,original_title,production_companies,production_countries,release_date,runtime,vote_average,vote_count
0,"Animation, Comedy, Family",en,Toy Story,Pixar Animation Studios,United States of America,1995-10-30,81.0,7.7,5415.0
1,"Adventure, Fantasy, Family",en,Jumanji,"TriStar Pictures, Teitler Film, Interscope Com...",United States of America,1995-12-15,104.0,6.9,2413.0
2,"Romance, Comedy",en,Grumpier Old Men,"Warner Bros., Lancaster Gate",United States of America,1995-12-22,101.0,6.5,92.0
3,"Comedy, Drama, Romance",en,Waiting to Exhale,Twentieth Century Fox Film Corporation,United States of America,1995-12-22,127.0,6.1,34.0
4,Comedy,en,Father of the Bride Part II,"Sandollar Productions, Touchstone Pictures",United States of America,1995-02-10,106.0,5.7,173.0
...,...,...,...,...,...,...,...,...,...
45460,"Drama, Action, Romance",en,Robin Hood,"Westdeutscher Rundfunk (WDR), Working Title Fi...","Canada, Germany, United Kingdom, United States...",1991-05-13,104.0,5.7,26.0
45462,Drama,tl,Siglo ng Pagluluwal,Sine Olivia,Philippines,2011-11-17,360.0,9.0,3.0
45463,"Action, Drama, Thriller",en,Betrayal,American World Pictures,United States of America,2003-08-01,90.0,3.8,6.0
45464,,en,Satana likuyushchiy,Yermoliev,Russia,1917-10-21,87.0,0.0,0.0
45465,,en,Queerama,,United Kingdom,2017-06-09,75.0,0.0,0.0

In [5]:
output_directory = "dataset"
output_filename = "cleaned_movies_data.csv"
output_path = os.path.join(output_directory, output_filename)

try:
    df.to_csv(output_path, index=False, encoding='utf-8')
    print(f"\nDataFrame zostaÅ‚ pomyÅ›lnie zapisany do pliku: {output_path}")
except Exception as e:
    print(f"\nWystÄ…piÅ‚ bÅ‚Ä…d podczas zapisywania pliku CSV: {e}")

DataFrame zostaÅ‚ pomyÅ›lnie zapisany do pliku: dataset\cleaned_movies_data.csv